version: "3.0"

services:
  backend:
    container_name: backend-container
    image: backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    # environment:
    #   POSTGRES_HOST: db
    #   POSTGRES_PORT: 5432
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: postgres
    #   POSTGRES_DB: my_db
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - backend
    
  postgres:
    container_name: postgres-container
    image: postgres:latest
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_db
    ports:
      - 5432:5432
    # env_file:
    #   - .env
    volumes:
      - data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - backend
  

volumes:
  data:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: $PWD/postgres_data/


networks:
  backend:
