version: '3'

services:
  web:
    container_name: app-container
    image: app
    build:
      context: ./pong-contest-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # environment:
    #   POSTGRES_HOST: db
    #   POSTGRES_PORT: 5432
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: postgres
    #   POSTGRES_DB: my_db
    depends_on:
      - postgres
    restart: on-failure
    
  postgres:
    container_name: postgres-container
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    # env_file:
    #   - .env
    restart: on-failure

